### ISSUE TITLE
Returning interfaces / auto create proxies

### ISSUE THREAD

**Issue by the-snork** [zyanfx/Zyan#10]
I just played around a bit with your framework and ended up having a question:

A proxy object returns an interface. Zyan complains if the class implementing the interface is not serializable. If it is, in fact a new instance is created on the client side.

How to accomplish having a proxy created automatically instead?

Something like:

interface IParent
{
    IChild GetChild();
}

interface IChild
{
}

class Child : IChild
{
}

I would like that when calling GetChild on the client side, a transparent proxy for the corresponding instance on the server side is created and not an own instance of Child.

**Comment by yallie** [comment]
Hello,

There are two kinds of component activations supported by Zyan: Singleton and Single-call.
Singleton is a single server-side object serving all incoming remote calls from the clients.
Single-calls components are instances created every time for every new remote call.
Looks like you're trying to achieve something in-between these two kinds,
a long-living stateful component on the server.

Stateful components are not supported by Zyan. If you're familiar with Remoting,
you may remember that stateful components bring a lot of complexity to Remoting
such as leases, sponsorship, distributed garbage collection concepts, etc.
And they really don't bring much value for your application in return.
So we chose to avoid this stuff in Zyan to keep things simple,
that's why we don't support stateful components other than singletons.

Technically, you still can use any native Remoting concepts in Zyan (just inherit your
Child class from MarshalByRefObject, and you get a long-living server component),
but I strongly advise against doing that. 

Perhaps if you describe your idea in more details, I could suggest a way of implementing it.

**Comment by yallie** [comment]
@fdemski I'm closing the issue, but feel free to ask further question and/or reopen as needed.

Regards, Alex
