### ISSUE TITLE
Is the execution of an event on the client asynchronious?

### ISSUE THREAD

**Issue by radio42** [zyanfx/Zyan#14]
I have a TcpDuplexServerProtocolSetup server, which implements the following service:

```
/// <summary>
/// Raised by the server to invoke the execution to resolve a macro on the client.
/// <para>The delegate must have the signature: string Func(string macro)</para>
/// </summary>
event Func<string, string> EvalMacroReceived;

/// <summary>
/// Executes a control-command on the server.
/// </summary>
/// <param name="command">The control-command to execute.</param>
/// <returns>The reply string.</returns>
string ExecuteCommand(ControlCommand command);
```
When I am calling the 'ExecuteCommand' method from the client, to invoke it on the server-side, all is fine!

The client subscribes to the 'EvalMacroReceived' event.
When the server now invokes this event, the related method is actually called on the client also just fine.
BUT, the invokation on the server immediately returns with a NULL return value.
Thus, the server is unable to retrieve the actual return value of the client.

This is how the server invokes the event:
```
internal string RaiseEvalMacroReceived(string macro)
{
    if (EvalMacroReceived != null)
    {
        try
        {
            return EvalMacroReceived(macro);
        }
        catch { return String.Empty; }
    }
    return String.Empty;
}
```

This is how the client handles the event:
```
TcpDuplexClientProtocolSetup protocol = new TcpDuplexClientProtocolSetup(true);
Connection = new ZyanConnection(serverUrl, protocol, Credentials, false, true);
Connection.PollingInterval = TimeSpan.FromSeconds(15);
Connection.PollingEnabled = true;

RemoteProxy = Connection.CreateProxy<MyService>();
RemoteProxy.EvalMacroReceived += RemoteProxy_EvalMacroReceived;

private string RemoteProxy_EvalMacroReceived(string macro)
{
    return "Test";
}
```

Any idea, if this is a bug or if I am doing anything wrong or if invoking an event on the client side is always asynchronious and as such I can never get the return value of the delegate function back correctly?!

I am pretty sure, that this had worked in v2.5 and got somehow broken in v2.8 - but I am not entirely sure.

Many Thanks in advance,
Bernd

**Comment by yallie** [comment]
Hello Bernd,

you're right, the events are called asynchronously since Zyan v2.4 (released in 2012).
There's an option to enable pre-2.4 synchonous behavior:
`ZyanSettings.LegacyBlockingEvents = true`, but I strongly advise against using it.
Let me explain the reasoning behind that.

Events are not callbacks. Server-side event can have (and typically do have) multiple
subscribers, on different machines, perhaps even scattered around the globe.  
Some clients do have good internet connection, and some don't.

When a server fires events synchronously, it's forced to wait until each client sends
back a response. It will likely time out serving the clients that cannot respond fast.
Suppose you have 1000 fast subscribers (responding within a few milliseconds) and
10 slow ones (within seconds). Many of these 1000 will suffer waiting for to be served 
while 10 slow clients are being processed. This is unfair, this approach cannot scale.

Another reason is the return value semantics. You can't easily restrict a server-side
event from accepting multiple subscriptions. If your multiple event handlers return
different values, what's the result of your operation then?

Last, but not least, is the issue with exceptions. If a synchronous event handler fires
an exception, it gets propagated back to the server (because the server initiated
the remote call). What it can do to this exception? Most likely, it can't event
deserialize the exception because the server is not supposed to know what libraries
its clients may use. If your console Linux server works with the database, and its
Windows clients use UI toolkit not available on Linux, how can we even load these
libraries to deal with the client's exceptions?

Due to these three reasons (scalability, return values, exceptions), Zyan v2.4 and later
treat events as one-way calls: they fire asynchronously, they don't have return values,
and they don't fire exceptions back to server.

But that only applies to events. You still can send a delegate from the client, store it
on the server (in a session variable, for example) and invoke it asynchronously. 
This delegate is guaranteed to belong to just one client, so the first two arguments 
(scalability and return values) don't apply. You only have to care about the exceptions:

```c#
// client code
var conn = new ZyanConnection("your server url");
var service = conn.CreateProxy<ICommandService>();
service.RegisterMacroCallback(this.EvaluateMacro);
service.ExecuteCommand(cmd);
...
private string EvaluateMacro(string macro) => return "Test";

// server code
public void RegisterMacroCallback(Func<string, string> evaluator)
{
    var sessionVars = ServerSession.CurrentSession.SessionVariables;
    sessionVars["MacroEvaluator"] = evaluator;
}

public string EvaluateMacro(string macro)
{
    try
    {
        var sessionVars = ServerSession.CurrentSession.SessionVariables;
        var evaluator = (Func<string, string>)sessionVars["MacroEvaluator"];
        return evaluator(macro);
    }
    catch (...)
    {
        // handle, log, etc.
    }
}
```

**Comment by radio42** [comment]
Many Thanks for the extensive explanation - and I fully agree!
Perfect, that you already posted an alternative, which I will try.

**Comment by radio42** [comment]
The client side code works fine of course.

But the server sided code not.
I expect/need to call the "EvaluateMacro" method from the server side.
However the "ServerSession.CurrentSession" is always NULL !
I assume this is, because there is no current 'client' session, as I call this method on the server side.

I further guess, that I need to register (on the server) to the host's 'ClientLoggedOn' event and then keep track of the client sessionIDs myself.
I can then further use the host's SessionManager.GetSessionBySessionID method to get all client sessions and then use this session to retrieve the SessionVariables.

**Comment by yallie** [comment]
Ah, you must be calling `EvaluateMacro` not during the remote call from a client,
but at any given time, like timer event, for example. In that case the server is not acting 
on behalf of a certain client, so `ServerSession == null` makes perfect sense.

You just need any other storage for the client's delegates. The options are:

1. If you have multiple clients, you're probably have to distinguish them somehow 
from one another (either by SessionID, or by user identity, or whatever else). 
You'll probably want something like a `Dictionary<Guid, Func<string, string>>`.
Here is a simple example, assuming clients indexed by their SessionIDs:

```c#
private static Dictionary<Guid, Func<string, string>> MacroEvaluators { get; set; } = new...

public void RegisterCallback(Func<string, string> evaluator)
{
     // CurrentSession is not null here, because this method is called by the client
     var sessionId = ServerSession.CurrentSession.SessionID;
     MacroEvaluators[sessionId] = evaluator;
}
```

2. If you only have one client at a time (say, if you have a P2P application),
then you'll just need a single property to store the callback itself:

```c#
private static Func<string, string> ClientMacroEvaluator { get; set; }

public void RegisterCallback(Func<string, string> evaluator)
{
     ClientMacroEvaluator = evaluator; // overwrite the last value
}
```

>I further guess, that I need to register (on the server) to the host's 'ClientLoggedOn' event and then keep track of the client sessionIDs myself.

Yes, that's just fine. Also, you can use `ClientLoggedOff` to delete the unused callbacks.

>I can then further use the host's SessionManager.GetSessionBySessionID method to get all client sessions and then use this session to retrieve the SessionVariables.

You don't really need `SessionVariables`, you're likely to have more comfort with
your own storage like a generic dictionary. `SessionVariables` are only helpful
when used in server methods called remotely, when they automatically point
to your current remote client's data.

Regards, Alex

**Comment by yallie** [comment]
Guess it's all clear now, so closing this as well.
