### ISSUE TITLE
Porting from  .Net framework to .Net core

### ISSUE THREAD

**Issue by PositiverHeld** [zyanfx/Zyan#20]
Hello

I am trying to port my project on .Net CORE (Visual Studio 2017 on Windows and OSX). Unfortunately, Zyan is only supported by .Net Framework.

error output:
> Install-Package : Das Paket Zyan 2.8.0 ist nicht mit netcoreapp1.1 (.NETCoreApp,Version=v1.1) kompatibel. Paket Zyan 2.8.0 unterstützt Folgendes:
> - monoandroid10 (MonoAndroid,Version=v1.0)
> - net35 (.NETFramework,Version=v3.5)
> - net40 (.NETFramework,Version=v4.0)
> - net45 (.NETFramework,Version=v4.5)
> - net46 (.NETFramework,Version=v4.6)
> ...

Is there a way to use the package also under .Net core?

Thx and cya Thommy

**Comment by yallie** [comment]
Hello Thommy!

Sorry, I've completely missed the notification for this issue.
The current version of Zyan uses .NET Remoting which is not available on .NET Core.
So Zyan can only be used on full .NET Framework.

Regards, Alex

**Comment by PositiverHeld** [comment]
Hello Alex,

Thank you for your reply and for the great work. 
Too bad it does not work under .Net Core ;(

Best regards,
Thommy

**Comment by yallie** [comment]
Yeah, sorry about that.

I have plans to decouple Zyan from Remoting so that it can plug in any RPC layer,
but that's reserved for the future (my company doesn't need it right away, 
and I don't have much spare time to play with it on my own).

Perhaps when it's done, Zyan could support much wider spectrum of platforms.

Cheers, Alex.
