### ISSUE TITLE
CurrentSession app-domain

### ISSUE THREAD

**Issue by csharpdeveloper12** [zyanfx/Zyan#28]
Hello yallie,

it's me again :)

I have a method "IProxy.Method" which invokes an external method in an external assembly (which references Zyan). This external method reads  "Zyan.Communication.ServerSession.CurrentSession.Identity.Name" and works with the property.

Now my question: Is it safe if multiple clients/users invokes "IProxy.Method"? My apprehension is, that the "context" ("CurrentSession") is mixed through the seperate instances, so that in the external method which is invoke from "UserA" in "CurrentSession" the identity from "UserB" is.
In [https://github.com/zyanfx/Zyan/blob/master/source/Zyan.Communication/ServerSession.cs](url) i have read by "CurrentSession" "This property doesn't cross application domain boundaries.". Are each Session in his own app-domain?

Thanks in advance
csharpdeveloper12

**Comment by yallie** [comment]
Hello,

>Is it safe if multiple clients/users invokes "IProxy.Method"? 

each client has its own thread-local copy of the current session, so yeah, it should be thread-safe.

>Are each Session in his own app-domain?

Yes, the session only exists in the application domain of ZyanComponentHost serving the current request. ServerSession doesn't travel between application domains (otherwise it would have leaked through to the client's appdomain as easily).

**Comment by csharpdeveloper12** [comment]
Hello yallie,

thank you a lot for clarify my question once again :)

**Comment by yallie** [comment]
You're welcome! :)
