### ISSUE TITLE
Event was not raised in client application

### ISSUE THREAD

**Issue by raminmjj** [zyanfx/Zyan#41]
I create a sample from your android client example.
I make Android app as a server and WinForm application as a client.
everything worked, but my custom event was not raised in client application.
where am I doing wrong?
thank you.
[sample code.zip](https://github.com/zyanfx/Zyan/files/1776310/tmp.zip)

**Comment by yallie** [comment]
Hi Ramin,

long story short, I think the problem is with `ThreadPool.QueueUserWorkItem`.
Try firing your event without any thread pool stuff (Zyan fires all events asynchronously anyway):

```csharp
private void DoSending(string p1, string p2)
{
	var obj = new MyEventArgs()
	{
		P1 = p1,
		P2 = p2,
		JobStatus = Status.Done
	};

	OnSendSmsEvent(obj);
}
```

Also, there is no point writing a try-catch when using `QueueUserWorkItem`.
`QueueUserWorkItem` won't propagate the exception back to where it was called:

```csharp
try
{
      QueueUserWorkItem(x => { throw new Exception("Boo!"); }); // goes unhandled
}
catch (Exception ex)
{
      // never goes here
      Console.WriteLine(ex.ToString());
}
```

Regards, Alex

**Comment by raminmjj** [comment]
Hi Alex,
thanks for your attention.
I removed threads. no exception accord and event was run over server, but not fired on client.

**Comment by yallie** [comment]
Hi Ramin,

I don't see the code that routes the events to the UI thread.
WinForm apps are single-threaded (as well as WPF and Android apps), 
so they can't properly handle events coming from other threads.
When a remote event occurs, it's handled by an arbitrary worker thread
of your WinForms app, and perhaps that's the problem.

Please try setting a breakpoint in the event handler to check
whether the event handler is actually executed or not.

To marshal an event to the UI thread, [use the Invoke method](https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/how-to-make-thread-safe-calls-to-windows-forms-controls).
Something like this:

```csharp
private void MyAppHubService_DoJobEvent(object sender, MyEventArgs e)
{
	// marshal the call to the UI thread
	if (InvokeRequired)
	{
		Invoke(new Action(() => MyAppHubService_DoJobEvent(sender, e)));
		return;
	}

	// we're in the UI thread now
	var msg = $"P1: {e.P1} \n P2:{e.P2} \n Status: {e.JobStatus.ToString()} \n Error Message: {e.ErrorMessage}";
	MessageBox.Show(msg);
}
```

**Comment by raminmjj** [comment]
Hi Alex,
thank you. it's worked. but response for first request take about 10-25 seconds and some times doesn't respond to first request. 
The other thing is, if I don't send a request for a minute, it will take about 5 seconds to get respond. is it normal?

**Comment by yallie** [comment]
Hello Ramin,

>but response for first request take about 10-25 seconds

That doesn't look normal.

I've seen big delays on my low-end phone when encryption was enabled (I assume that's because of the slow arbitrary-precision math when RSA keys are negotiated, but never tried to investigate it in details).

Make sure that channel encryption is disabled in TcpEx protocol and check if it helps with the delays. Try setting the `encryption` parameter in both protocol constructors to `false`. Client and server's encryption flag should be set to the same value, or the connection will fail.

Regards, Alex

**Comment by raminmjj** [comment]
Hi Alex,
I set encryption to false, now response from mobile server is faster than before. but first request doesn't respond.

Thank you.

**Comment by yallie** [comment]
>I set encryption to false, now response from mobile server is faster than before.

Cool!

>but first request doesn't responded.

Well, that may be a bug :)

As a workaround, try firing the first event just after creating the proxy and ignoring that event. This approach will work with the current version of Zyan and it won't break with the future versions when/if the bug is fixed.

Regards, Alex.
