### ISSUE TITLE
Can an object returned by a service still be hooked into Zyan?

### ISSUE THREAD

**Issue by ErrCode** [zyanfx/Zyan#47]
Hi!

This is a question about how to use Zyan, given this use case where the server can determine what service the client would get based on the parameter it sent in (`serviceType`):

```
// Pseudo code for the main service handler IServices
public interface IServices
{
     IClientServiceHandle GetServiceHandle(string serviceType);
     // the server will create a concrete class of IClientServiceHandle and return this
}

delegate void MessageReceivedEventHandler(string message);
public interface IClientServiceHandle : IDisposable
{
     event MessageReceivedEventHandler MessageReceived;
     void Close();
}
```

What I want is for the handler object returned by `GetServiceHandle(...)` to still be connected via Zyan, so that the server can Invoke the `MessageReceived` event on it's side which would then trigger the `MessageReceived` event on the client side. From my tests, it seems that the object returned to the client side is disconnected from the server side and thus won't receive the event.

As an example (fictional), let's say the `serviceType` was "HourlyAlarm": 

- the server will invoke `MessageReceived` on a timer at the hourly interval
- the client continues receiving such messages until closed/disposed

Q1): Is what I'm trying to achieve at all possible using Zyan?

Q2): If this design can be made to work, will it be possible that the server can also call close/dispose (e.g. when the server is shutdown) and that state is reflected by the client?

**Comment by yallie** [comment]
Hello, returning services is not supported. Server can only return serializable objects.

Also, Zyan server is stateless, so your remote components are either single-call components (new instance is created on every call) or singletons (single component instance is shared by all clients). There is no built-in «component instance per session» concept or something like that.

Q1. If you need remote server to keep track of some stateful components, you can implement it using a singleton. It would keep a dictionary of created services for each session and dispatch all incoming calls. So that's not available right out of the box, but it's possible to implement.

Q2. Think of it just as another event, ServerClosed. When a server is about to close, it fires an event to all connected client and shuts down. Clients receive an event and mark the sender server as offline.

**Comment by ErrCode** [comment]
Thank you for your reply. 

I see. So as you said, the object returned by a service can not be a service itself. Since I'm unable to return a service directly, then there is no way for the `GetServiceHandle` idea to work. 

Q1. I assume you're referring to this kind of ability?
```
static HourlyAlarm s_alarm1PerHour = new HourlyAlarm();
static DailyAlarm s_alarm1PerDay = new DailyAlarm();
// and we register this in the startup code:
host.RegisterComponent<IAlarm, HourlyAlarm>(s_alarm1PerHour);
host.RegisterComponent<IAlarm, DailyAlarm>(s_alarm1PerDay);
```
And the client would be able to get the appropriate service via `conn.CreateProxy<IAlarm>("HourlyAlarm")` and `conn.CreateProxy<IAlarm>("DailyAlarm")` respectively?

Q2. I see. Sounds good.
