### ISSUE TITLE
64bit dll

### ISSUE THREAD

**Issue by BLIZZARD123** [zyanfx/Zyan#48]
Dear team,

thank you for providing us such a great framework.
while implementing this framework in my applications I faced some issues regarding 32bit and 64bit.

My applications are only running in 64bit (c# > properties > 64bit - not anycpu!!) and cant run your dll's (Zyan.SafeDeserializationHelpers.dll, ZyanCommunication.dll because they'd compiled with anycpu / or 32 bit.

Is it possible to provide me a x64 version of your framework?

Thank you
BR

**Comment by yallie** [comment]
Hi @BLIZZARD123, thanks for your kind words!

AnyCPU assembly can be loaded in both 32-bit and 64-bit modes.
Even if the host application is compiled as x86 or x64, it loads AnyCPU assemblies just fine.
We have a bunch of x86-, x64- and anycpu- applications all using the same Zyan binaries.

If you're facing some bitness issues (invalid module format exceptions, etc), 
it's likely they're caused by other dependencies.

Thanks, Alex

**Comment by BLIZZARD123** [comment]
Dear Alex,

Thank you for your fast reply. In the meantime I found a way to compile everything in x64

But my application still don’t want to accept the library. 

Is it possible to contact you outside of github to describe my issue in detail? Because I would like to use your framework, it’s really nice and easy to use. 
BTW we can write in German as well. 

BR
blizz

Von meinem iPhone gesendet

Am 25.10.2018 um 19:29 schrieb Alexey Yakovlev <notifications@github.com>:

Hi @BLIZZARD123, thanks for your kind words!

AnyCPU assembly can be loaded in both 32-bit and 64-bit mode.
Even if the host application is compiled as x86 or x64, it loads AnyCPU assemblies just fine.
We have a bunch of x86-, x64- and anycpu- applications all using the same Zyan binaries.

If you're facing some bitness issues (invalid module format exceptions, etc),
it's likely they're caused by other dependencies.

Thanks, Alex
