### ISSUE TITLE
Registration to next use SrpAuthenticationProvider

### ISSUE THREAD

**Issue by aconqorf** [zyanfx/Zyan#58]
Hello @yallie, how can I register my account for further interaction of account with `ISrpAccountRepository`? Should I declare a separate `ZyanComponentHost` for this? If it so, then how best to interact with several `ZyanComponentHost`, so that one works for registration and other for working with clients (after successfully authorization)?

**Comment by yallie** [comment]
Hello @aconqorf ,

so you need to allow users to register themselves within the app?

Your suggested approach is fine, you can use a separate `ZyanComponentHost` without authentication, that only allows registering new accounts and nothing more (i.e. that hosts only your app-specific `IRegistrationService`). To connect to this host, you'll need a separate connection, with no credentials. Each host will have its own endpoint URL.

Once a user completes the registration, it closes the unathenticated connection and re-connects to the main application host using SRP credentials. I think there is nothing wrong with this approach.

But there is an easier alternative: you can add a built-in guest account used for unauthenticated users and use single `ZyanComponentHost` for both guests and privileged users. When a user is logged in as guest, no operations are allowed except for the new user registration. In your services you can use `ServerSession.CurrentSession.Identity` to check who is logged in, i.e.:

```csharp
if (ServerSession.CurrentSession.Identity.Name == "guest")
{
    throw new SecurityException("Guest access to this service is not allowed").
}
```

Of course, a user still needs to log out as guest and re-login using his normal login and password once the registration is complete. That means closing and re-opening the connection using another credentials.

**Comment by aconqorf** [comment]
Thank you, @yallie.

P.S. What about [Zyanea](https://github.com/yallie/Zyanea)? Do you plan to continue to develop?

**Comment by yallie** [comment]
Zyanea is a proof of concept, an experiment, so I'm not sure about its future.
My next project requires Javascript/C# interoperation, that's why I'm currently working 
on another kind of library, namely [JsonServices](https://github.com/yallie/JsonServices).

It's more message-oriented, and modelled after ServiceStack, not Zyan or Zyanea.
It's based on JSON-RPC 2.0 standard and supports .NET Core out of the box.
It has SRP authentication, events, it doesn't need transparent proxies and doesn't support LINQ.
Its primary transport is web sockets, and C# version also supports ZeroMQ.
