### ISSUE TITLE
Equals different between proxies

### ISSUE THREAD

**Issue by csharpdeveloper12** [zyanfx/Zyan#8]
Hello,

i have an issue when i retrieve objects with nested objects.

There are two Proxies with the Functions:
`GetAutos1()`, `GetAutos2()` and `GetMarken()`:

```
public interface IAuto
{
	System.Collections.Generic.List<Auto> GetAutos1();		
	System.Tuple<System.Collections.Generic.List<Auto>, System.Collections.Generic.List<Marke>> GetAutos2();
}
```

```
public interface IMarke
{
	System.Collections.Generic.List<Marke> GetMarken();
}
```

```
[System.Serializable]
public class Auto
{
	public System.Guid Id { get; set; }
	public string Farbe { get; set; }
	public Marke Marke { get; set; }
}
```

```
[System.Serializable]
public class Marke
{
	public System.Guid Id { get; set; }
	public string Name { get; set; }
}
```

> ## **Szenrio 1**
> `var marken = connection.CreateProxy<Shared.IMarke>("Marke").GetMarken();`
> `var auto = connection.CreateProxy<Shared.IAuto>("Auto").GetAutos1()[0];`
> 
> But if i use `object.Equals(marken[0], auto.Marke)` ... `object.Equals(marken[n], auto.Marke)`, it's allways `False`.

> ## **Szenrio 2**
> `var items = connection.CreateProxy<Shared.IAuto>("Auto").GetAutos2();`
> `var marken = items.Item2;`
> `var auto = items.Item1[0];`
> 
> Now it works correctly. If i use `object.Equals(marken[0], auto.Marke)` ... `object.Equals(marken[n], auto.Marke)`, n-1 times the Result is `False` and one time the Reult is `True`.

What can i do, that "Szenario 1" works also correct? Or is it an issue in Zyan?

Thanks in advance

**Comment by yallie** [comment]
Hello, this issue isn't specific to Zyan.

If you don't override Equals method in your class, it checks for the **reference** equality, i.e.:

```csharp
var marke1 = new Marke { Id = Guid.Empty, Name = "None" };
var marke2 = new Marke { Id = Guid.Empty, Name = "None" }; // all the same
Console.WriteLine(object.Equals(marke1, marke2)); // this line writes: False
```

Exact copies of your class Marke aren't equal unless they are **the same instance**:

```csharp
var marke1 = new Marke { Id = Guid.Empty, Name = "None" };
var marke2 = marke1; // points to the same exact instance in memory
Console.WriteLine(object.Equals(marke1, marke2)); // this line writes: True
```

When you deserialize an object (for example, as a result of a remote call, either in Zyan, of WCF, or Rest, or whatever), you get a copy of it. The next deserialization or remote call will give you yet another instance, and so on. And different instances aren't equal unless you override Equals method, like class System.String does.

>**Szenrio 2**
>Now it works correctly. If i use object.Equals(marken[0], auto.Marke) ... object.Equals(marken[n], auto.Marke), n-1 times the Result is False and one time the Reult is True.

Why are they equal in this scenario then? Because they're parts of a single object graph. Two references within server's graph points to the same Marke instance, and when you deserialize that graph on a client, you get exact copy of it. So these two references within client's graph also point to the same Marke instance, now in the client's memory. Since it's the same instance, `object.Equals` returns `True`.

Now back to your question.

>What can i do, that "Szenario 1" works also correct? 

Just override Equals and GetHashCode methods in your classes like this:

```csharp
[System.Serializable]
public class Marke
{
	public System.Guid Id { get; set; }
	public string Name { get; set; }

        public override bool Equals(object obj)
        {
             var other = obj as Marke;
             if (other == null) return false;
             return Id == other.Id && Name == other.Name;
        }

        public override int GetHashCode()
        {
             return Id.GetHashCode();
        }
}
```

**Comment by csharpdeveloper12** [comment]
Hello yallie,

thank you for fast reply :)

It works perfect :)

For my understanding, "Szenario 1" doesn't works because the two objects are from different (stupidly expressed) "serialization tasks"?

Remoting is verry difficult but i am happy that Zyan makes a lot in the background :)

Best regards

**Comment by yallie** [comment]
You're welcome!

>For my understanding, "Szenario 1" doesn't works because the two objects are from different (stupidly expressed) "serialization tasks"?

Yes, exactly: two remote calls — two deserializations — two unrelated instances.

If your class is serializable, it makes sense to override Equals/GetHashCode method to ensure that different copies of your class are treated as the same value. When a class is serializable, it's easy to create a copy of it accidentally.

**Comment by csharpdeveloper12** [comment]
Hello yallie,

tanks for your explanation. Now it's clear to me and i have learned something new :)

Tanks a lot and best regards
